ARG GRIDAPPSD_VERSION_LABEL=:rc2

FROM gridappsd/gridappsd_base${GRIDAPPSD_VERSION_LABEL}

# Copy the local GOSS and GOSS-GridAPPS-D source code (cloned by build-images.sh)
COPY GOSS ${TEMP_DIR}/GOSS
COPY GOSS-GridAPPS-D ${TEMP_DIR}/GOSS-GridAPPS-D

RUN cd ${TEMP_DIR}/GOSS-GridAPPS-D && \
  pip3 install -r ./services/fncsgossbridge/requirements.txt && \
  pip3 install -r ./services/helicsgossbridge/requirements.txt && \
  ./gradlew dist && \
  cp ./applications /gridappsd/applications -R && \
  cp ./services /gridappsd/services -R && \
  cp -r ./build/launcher/* ${GRIDAPPSD}/lib/ && \
  rm -rf ${TEMP_DIR}/GOSS-GridAPPS-D && \
  rm -rf ${TEMP_DIR}/GOSS && \
  rm -rf /var/cache/apt/archives/* && \
  rm -rf /root/.cache/pip/wheels

COPY GOSS-GridAPPS-D/run-gridappsd.sh /gridappsd/run-gridappsd.sh
RUN chmod +x /gridappsd/run-gridappsd.sh

# Uncomment the following to have debug tools in the image
# RUN apt-get update && apt-get install -y net-tools vim

# Ensure proper ownership for gridappsd user (from base image)
RUN chown -R gridappsd:gridappsd /gridappsd

VOLUME /gridappsd/conf /tmp/gridappsd/log

# Should match what is in conf/pnnl.goss.core.server.cfg and
# conf/pnnl.goss.core.client.cfg
EXPOSE 61616 61613 61614

USER gridappsd
WORKDIR /gridappsd
# CMD ["./gridappsd.run.sh"]
