# This is a xenial base with python
FROM python:3.10.17-slim-bullseye 

RUN apt-get update \
    && apt-get install -y \
       wget \
       git \
       cmake \
       ca-certificates \
       openssl \
       # These two for activemq \       
       libaprutil1-dev \
       mariadb-client \
       python3-dev \ 
       python3-pip \
       python3-setuptools \
       sudo \
       vim \
       liblapack-dev \
       libblas-dev \
       libssl-dev \
       libboost-dev \
       libxerces-c-dev \
       libzmq5-dev \
       m4 \
       procps \
       libtool \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt/archives/*

WORKDIR /gridappsd

ENV GRIDAPPSD=/gridappsd
ENV GLD_INSTALL=${GRIDAPPSD}
ENV TEMP_DIR=/tmp/source
ENV HELICS_INSTALL=/usr/local/lib/python3.10/site-packages/helics/install
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HELICS_INSTALL}/lib64

# ----------------------------------------------------
# INSTALL Helics
# ----------------------------------------------------
RUN pip install 'helics[cli]'

# ----------------------------------------------------
# INSTALL Gridlab-D
# ----------------------------------------------------
RUN mkdir ${TEMP_DIR} \
   && cd ${TEMP_DIR} \
   && git clone https://github.com/gridlab-d/gridlab-d.git -b develop --single-branch \
   && cd ${TEMP_DIR}/gridlab-d \
	&& git submodule update --init \
	&& mkdir cmake-build \
	&& cd cmake-build \
	&& cmake -DCMAKE_INSTALL_PREFIX=${GLD_INSTALL} -DGLD_USE_HELICS=ON -DGLD_HELICS_DIR=${HELICS_INSTALL}/lib64/cmake/HELICS ../ \
	&& cmake --build . -j20 --target install \
	&& cd /tmp \
   && /bin/rm -r ${TEMP_DIR}/gridlab-d

# ----------------------------------------------------
# INSTALL Java
# ----------------------------------------------------
RUN cd ${TEMP_DIR} \
    && wget https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u322-b06/OpenJDK8U-jdk_x64_linux_hotspot_8u322b06.tar.gz \
    && mkdir /usr/lib/jvm \
    && cd /usr/lib/jvm \
    && tar -xzf ${TEMP_DIR}/OpenJDK8U-jdk_x64_linux_hotspot_8u322b06.tar.gz \
    && update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk8u322-b06/bin/java 1 \
    && /bin/rm ${TEMP_DIR}/OpenJDK8U-jdk_x64_linux_hotspot_8u322b06.tar.gz
     

# ----------------------------------------------------
# INSTALL Activemq c++ extensions
# ----------------------------------------------------
RUN cd ${TEMP_DIR} \
    && wget http://archive.apache.org/dist/activemq/activemq-cpp/3.9.5/activemq-cpp-library-3.9.5-src.tar.gz \
    && tar -xzf activemq-cpp-library-3.9.5-src.tar.gz \
    && cd activemq-cpp-library-3.9.5 \
    && ./configure --prefix=${GRIDAPPSD} \
    && make \
    && make install \
    && cd /tmp \
    && /bin/rm -r ${TEMP_DIR}/activemq-cpp-library-3.9.5 \
    && /bin/rm -r ${TEMP_DIR}/activemq-cpp-library-3.9.5-src.tar.gz 

# ----------------------------------------------------
# INSTALL Python requirements 
# ----------------------------------------------------
COPY ./requirements_base.txt /gridappsd/requirements_base.txt
RUN pip install -r /gridappsd/requirements_base.txt && \
  rm -rf /root/.cache/pip/wheels

# ----------------------------------------------------
# INSTALL State Estimator
# ----------------------------------------------------
RUN cd ${TEMP_DIR} \
  && git clone https://github.com/GRIDAPPSD/gridappsd-state-estimator \
  && cd gridappsd-state-estimator \
  && git clone https://github.com/GRIDAPPSD/SuiteSparse \
  && git clone https://github.com/GRIDAPPSD/json \
  && LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${TEMP_DIR}/gridappsd-state-estimator/SuiteSparse/lib/ make -C SuiteSparse LAPACK=-llapack BLAS=-lblas \
  && make -C state-estimator AMQINCPATH3=/gridappsd/include/activemq-cpp-3.9.5 \
  && mkdir -p /gridappsd/services/gridappsd-state-estimator \
  && rm -rf .git SuiteSparse/.git json.git \
  && cp -r * /gridappsd/services/gridappsd-state-estimator \
  && cp /gridappsd/services/gridappsd-state-estimator/state-estimator.config /gridappsd/services/ \
  && cd /tmp \
  && /bin/rm -r ${TEMP_DIR}/gridappsd-state-estimator

# ----------------------------------------------------
# INSTALL Ochre
# ----------------------------------------------------
#RUN cd /gridappsd/services/ \
#    && git clone https://github.com/gridappsd/gridappsd-ochre \
#    && cd /gridappsd/services/gridappsd-ochre \
#    && pip install -r requirements.txt \
#    && rm -rf /root/.cache/pip/wheels 

#ENV PYTHONPATH=${PYTHONPATH}:/gridappsd/services/gridappsd-ochre
#ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64

# ----------------------------------------------------
# Set the JAVA_HOME variable 
# ----------------------------------------------------
ENV JAVA_HOME /usr/lib/jvm/jdk8u322-b06
