FROM node:20-alpine

WORKDIR /viz

ARG REPO=GRIDAPPSD/viz
ARG BRANCH=master
ARG ARCHIVE_FILE=$BRANCH.zip

# Install dependencies for downloading and extracting
RUN apk add --no-cache wget unzip ca-certificates

# Download and extract viz repository
RUN wget -O $ARCHIVE_FILE https://github.com/$REPO/archive/$ARCHIVE_FILE && \
    unzip $ARCHIVE_FILE && \
    mv viz-$BRANCH viz && \
    rm $ARCHIVE_FILE

# Install global npm packages
RUN npm install -g typescript typings webpack


#RUN git clone https://github.com/GRIDAPPSD/viz -b master --single-branch
#RUN git clone https://github.com/craig8/viz -b dockerized --single-branch

WORKDIR /viz/viz

RUN npm install
RUN webpack

# Create gridappsd user with passwordless sudo (Alpine syntax)
RUN apk add --no-cache sudo && \
    addgroup -g 1000 gridappsd && \
    adduser -D -u 1000 -G gridappsd -h /viz -s /bin/sh gridappsd && \
    echo 'gridappsd ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    chown -R gridappsd:gridappsd /viz

ENV VIZ_PORT=8082
ENV PORT=${VIZ_PORT}
EXPOSE ${VIZ_PORT}

USER gridappsd

CMD ["npm", "start"]
